---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# newspaper

The goal of newspaper is to extract contents from Newspaper's website.

## Installation

You can install the released version of newspaper from [Github](https://github.com/forkonlp/newspaper) with:

``` r
# install.packages("remotes")
remotes::install_github("forkonlp/newspaper")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(newspaper)
library(dplyr)

np_news("http://www.100ssd.co.kr/news/articleView.html?idxno=62271") %>% glimpse()
np_news("http://1318virus.net/?p=1129") %>% glimpse()
np_news("http://www.1gan.co.kr/news/articleView.html?idxno=179119") %>% glimpse()
np_news("http://www.ablenews.co.kr/News/NewsContent.aspx?CategoryCode=0014&NewsCode=001420190620151645090595") %>% glimpse()

```

## Target Site

[미디어맵](http://www.mediamap.co.kr/)에 등록된 사이트

